name: ocr-livre
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - requests==2.33.0
    - natsort==8.4.0
    - numpy==2.2.6
    - openai==2.30.0
    - paddlepaddle==3.3.1
    - paddlex[ocr]==3.4.3
    - pymupdf==1.25.3
