"""
postprocess.py — OCR text cleanup before writing to the final Markdown
"""

import re
import logging

import markdownify

from config import Config

logger = logging.getLogger(__name__)


def clean_page(text: str, cfg: Config, no_layout: bool = False) -> str:
    """
    Applies cleanups enabled in config:
      - removal of isolated page numbers
      - rejoining of hyphenated words at line end (ex: condi-\ntion)
      - reduction of excessive blank lines
    no_layout: True if the page was processed without layout detection (fallback).
    """
    if cfg.remove_isolated_page_numbers:
        text = re.sub(r'^\s*\d{1,3}\s*$', '', text, flags=re.MULTILINE)

    if cfg.rejoin_hyphenated_words:
        text = re.sub(r'(\w)-\n(\w)', r'\1\2', text)
        # Continuation lowercase after hyphen with double break (layout or no-layout)
        # Restricted to lowercase to avoid merging with next title/paragraph
        text = re.sub(r'(\w)-\n\n([a-zéèêëàâîïôùûüçœ])', r'\1\2', text)
        if no_layout:
            # Remove generation loops: substring ≥15 chars repeated 3+ times
            text = re.sub(r'(.{15,}?)\1{2,}', r'\1', text)
        text = re.sub(r'(\w)- (\w)', r'\1\2', text)
        # Paragraph cut mid-sentence: line ending with lowercase/comma
        # followed by empty paragraph then lowercase or '('
        text = re.sub(r'([a-zéèêëàâîïôùûüçœ,])\n\n(\(|[a-zéèêëàâîïôùûüçœ\d])', r'\1 \2', text)

    if cfg.collapse_blank_lines:
        text = re.sub(r'\n{3,}', '\n\n', text)

    return text.strip()


def strip_table_styles(text: str) -> str:
    """
    Removes inline styles from table tags generated by PaddleOCR (pretty=True).
    <div style="..."> (captions, titles) are kept.
    Always applied, regardless of cfg.postprocess.
    """
    text = re.sub(r"<table\b[^>]*\bstyle='[^']*'", '<table align="center" border=1', text)
    text = re.sub(r"<(t[dh])\b[^>]*\bstyle='[^']*'>", r"<\1>", text)
    return text


_CODE_SPAN_RE = re.compile(r'`[^`]*`')
_BLOCK_TAG_RE = re.compile(r'<(?:div|p|table|h[1-6]|ul|ol|li|blockquote|pre)[\s>]', re.IGNORECASE)


def _protect_code_spans(text: str) -> tuple[str, list[str]]:
    placeholders: list[str] = []
    def replace(m: re.Match) -> str:
        placeholders.append(m.group(0))
        return f'\x00CODE{len(placeholders) - 1}\x00'
    protected = _CODE_SPAN_RE.sub(replace, text)
    return protected, placeholders


def _restore_code_spans(text: str, placeholders: list[str]) -> str:
    for i, ph in enumerate(placeholders):
        text = text.replace(f'\x00CODE{i}\x00', ph)
    return text


class _PureMarkdownConverter(markdownify.MarkdownConverter):
    """Custom markdownify converter that preserves existing Markdown syntax
    and converts <sup> / <sub> to ^text^ / ~text~."""

    def convert_sup(self, el, text, parent_tags):
        return '^%s^' % text if text else ''

    def convert_sub(self, el, text, parent_tags):
        return '~%s~' % text if text else ''


def html_to_markdown(text: str) -> str:
    """
    Converts HTML tags (tables, figures, superscripts, etc.) generated by
    PaddleOCR into pure Markdown. Preserves existing Markdown text.

    Handles: <table>, <img>, <div>, <sup>, <sub>, <b>, <strong>, <i>, <em>, <br>.
    Unknown tags are unwrapped (children kept).
    """
    protected, placeholders = _protect_code_spans(text)

    # markdownify's process_text() collapses \n\n → \n in every bare text node
    # (it normalizes whitespace). To preserve paragraph breaks, we split on \n\n
    # and wrap each bare paragraph (no block-level HTML) in <p> tags.
    segments = protected.split('\n\n')
    wrapped: list[str] = []
    for seg in segments:
        seg = seg.strip()
        if not seg:
            continue
        if _BLOCK_TAG_RE.search(seg):
            # Already contains block-level HTML — leave as-is
            wrapped.append(seg)
        else:
            # Bare text: normalize internal whitespace, then wrap in <p>
            seg = ' '.join(seg.split())
            wrapped.append(f'<p>{seg}</p>')
    protected = '\n\n'.join(wrapped)

    converter = _PureMarkdownConverter(
        strip=['style'],
        escape_asterisks=False,
        escape_underscores=False,
        escape_misc=False,
    )
    result = converter.convert(protected)
    return _restore_code_spans(result, placeholders)


def extract_page_number(text: str) -> tuple[str | None, str]:
    """
    Extracts printed page number(s) from the first/last N lines.
    Returns (page_number, cleaned_text) where page_number is None, "42", or "42-43".

    Rule: single number, or two consecutive numbers → range; otherwise first found.
    Candidate lines are always removed from the returned text.
    """
    N = 5
    lines = text.splitlines()
    n = len(lines)
    search = set(range(min(N, n))) | set(range(max(0, n - N), n))

    found = []
    for i in sorted(search):
        m = re.match(r'^\s*(\d{1,3})\s*$', lines[i])
        if m:
            found.append((i, int(m.group(1))))

    if not found:
        return None, text

    nums = [num for _, num in found]
    if len(nums) >= 2 and nums[1] == nums[0] + 1:
        label = f"{nums[0]}-{nums[1]}"
    else:
        label = str(nums[0])

    remove = {i for i, _ in found}
    cleaned = '\n'.join(line for i, line in enumerate(lines) if i not in remove)
    return label, cleaned


def format_page_block(page_id: str, text: str, page_number: str | None = None) -> str:
    label = f"{page_id} (p. {page_number})" if page_number else page_id
    return f"\n\n<!-- Page {label} -->\n\n{text}\n"


def format_error_block(page_id: str, error: str) -> str:
    return f"\n\n<!-- Page {page_id} — ERROR: {error} -->\n"


def extract_done_pages(output_text: str) -> set[str]:
    return set(re.findall(r'<!-- Page (\S+)', output_text))


def apply_header_detection(text: str, header_patterns: list[tuple[str, int]]) -> str:
    """
    Detects and adds markdown headers on the complete output file.
    Applied once after assembling all pages.

    Anti-false-positive heuristics:
      - Line already a header (starts with #) → ignored
      - Line > 120 chars → too long to be a header
      - Line ending with , ; : → body text
      - HTML comment line → ignored
    """
    lines = text.splitlines()
    result = []
    for line in lines:
        stripped = line.strip()
        if (not stripped
                or stripped.startswith('#')
                or stripped.startswith('<!--')
                or len(stripped) > 120
                or stripped.endswith((',', ';', ':'))):
            result.append(line)
            continue
        matched = False
        for pattern, level in header_patterns:
            if re.match(pattern, stripped):
                result.append('#' * level + ' ' + stripped)
                matched = True
                break
        if not matched:
            result.append(line)
    return '\n'.join(result)


def fix_image_paths(text: str, page_id: str, figures_rel: str) -> str:
    """
    Fixes relative paths to images generated by PaddleOCR.
    PaddleOCR uses 'imgs/...' relative to the page folder.
    When combining all markdowns into a single file, we recalculate
    the relative path from the output file's folder.
    """
    prefix = figures_rel.replace("\\", "/")
    return re.sub(r'src="imgs/', f'src="{prefix}/{page_id}/imgs/', text)
